### ISSUE TITLE
512*1024分辨率的训练结果

### ISSUE THREAD

**Issue by fjqfjqfjqfjqfjqfjqfjq** [haritsahm/pytorch-DMANet#6]
您好，我用512*1024的分辨率训练模型，结果模型的精度很低，只有40%左右，很困惑，一直没有找到原因，想问一下您知道这是什么原因吗？

**Comment by haritsahm** [comment]
Thank you for your interest with my work. Unfortunately, I also experience the same thing. I haven't figure out the number of channels from author for each LERB block in [dma_net.py#L34](https://github.com/haritsahm/pytorch-DMANet/blob/683354292141863a8d07bba421da1526d670bc91/src/models/components/dma_net.py#L34), so I only use numbers that fulfills inference time (FPS) and parameter size (M). I also don't have the hardware to experiment with.

I'll update the script soon so that you can run multiple experiments to find the best channel combinations

**Comment by haritsahm** [comment]
@fjqfjqfjqfjqfjqfjqfjq  Please check the latest PR to see the changes especially on how to tune the model hyperparameters.

You should tune the `low_level_features` and `high_level_features`.

- high_level_features: its the CBR ([upmid_cbr](https://github.com/haritsahm/pytorch-DMANet/blob/main/src/models/components/dma_net.py#L74)) input size after addition ops between `sub-network 3` and `sub-network 4` in the upscaling pipeline.

- low_level_features: its the CBR ([uplow_cbr](https://github.com/haritsahm/pytorch-DMANet/blob/main/src/models/components/dma_net.py#L76)) input size after addition ops between `sub-network 2` and `upmid_cbr` in the upscaling pipeline.

You should simply run it with `python train.py experiment=cityscape.yaml hparams_search=dmanet_optuna data_dir=/path/to/cityscape/fiftyone_segmentation_format`

**Comment by fjqfjqfjqfjqfjqfjqfjq** [comment]
Thank you very much for your valuable help. I will try it later.
